library(Matrix)
library(arules)
library(arulesViz)
library(grid)
library(arulesViz)
library(datasets)
data("Groceries")
#itemFrequencyPlot(Groceries,topN=20,type="absolute")

rules <- apriori(Groceries, parameter = list(supp = 0.001, conf = 0.8))
options(digits=2)
inspect(rules[1:5])
rules<-sort(rules, by="confidence", decreasing=TRUE)
plot(rules,method="graph",interactive=TRUE,shading=NA)
